"""Render systemd unit file text for a job. Pure string templating, no I/O here."""

from __future__ import annotations

import shlex

from pereprava.logic.command import build_argv
from pereprava.model.job import Job

UNIT_PREFIX = "pereprava-job-"
GENERATED_HEADER = "# Generated by Pereprava — DO NOT EDIT.\n"


def unit_basename(slug: str) -> str:
    return f"{UNIT_PREFIX}{slug}"


def render_service_unit(job: Job) -> str:
    argv = build_argv(job)
    exec_start = shlex.join(argv)
    return (
        GENERATED_HEADER
        + f"# Edit via the Pereprava app, or delete ~/.config/pereprava/jobs/{job.slug}.json to remove.\n"
        + "\n"
        + "[Unit]\n"
        + f"Description=Pereprava backup job: {job.name}\n"
        + "\n"
        + "[Service]\n"
        + "Type=oneshot\n"
        + f"ExecStart={exec_start}\n"
        + f"StandardOutput=append:{job.log_path}\n"
        + f"StandardError=append:{job.log_path}\n"
    )


def render_timer_unit(job: Job) -> str:
    return (
        GENERATED_HEADER
        + "\n"
        + "[Unit]\n"
        + f"Description=Timer for Pereprava backup job: {job.name}\n"
        + "\n"
        + "[Timer]\n"
        + f"OnCalendar={job.schedule.on_calendar}\n"
        + "Persistent=true\n"
        + f"RandomizedDelaySec={job.schedule.randomized_delay_sec}\n"
        + "\n"
        + "[Install]\n"
        + "WantedBy=timers.target\n"
    )
